### ISSUE TITLE
Question: Why are assertions of a method in `ClientTest` disabled?

### ISSUE THREAD

**Issue by arueckauer** [laminas/laminas-json-server#6]
What is the reason, that the assertions of `ClientTest::testLastRequestAndResponseAreSetAfterRpcMethodCall()` are commented out?

Could not find any hints in Git history (change was made prior to what is available in Git history).

Tests are green locally (PHP 7.2, Windows 10), if I re-active them.

https://github.com/laminas/laminas-json-server/blob/8b21392c095568888dc19d3634b628678f477397/test/ClientTest.php#L86-L87

**Comment by michalbundyra** [comment]
@arueckauer 
Looks like these has been added here:
https://github.com/zendframework/zendframework/commit/63ca9e8eef500f02aba398b21e99fecfa77a3ea1

But from the beginning these were commented out.
Just try to find out if these makes sense, and if so - uncomment :)

**Comment by arueckauer** [comment]
The tests make sense. I'll provide a PR for reactivation.
